[0;33m--- Warning: GDB cannot open serial ports accessed as COMx[0m
[0;33m--- Using \\.\COM17 instead...[0m
[0;33m--- esp-idf-monitor 1.5.0 on \\.\COM17 115200[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpqpsc69jc"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpqpsc69jc': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmp50w2xrj9"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmp50w2xrj9': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpapkxn9cd"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpapkxn9cd': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpbst_ndzr"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpbst_ndzr': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpcjifon25"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpcjifon25': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmp4whs007d"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmp4whs007d': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmp8a5no7tl"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmp8a5no7tl': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpkkdvbac5"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpkkdvbac5': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmp76y4e3mm"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmp76y4e3mm': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpqxyi9lk5"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpqxyi9lk5': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmprbqhasfd"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmprbqhasfd': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpqzvjpt6c"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpqzvjpt6c': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpg8_j18_1"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpg8_j18_1': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpf3aj_87p"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpf3aj_87p': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40380880: panic_abort at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/panic.c:468
0x403852d6: __ubsan_include at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Esp-idf\\Esp32MCU_jigaku\\Esp32_c3mini1_project\\max30102_test\\build\\max30102_test.elf', '-ex', 'target remote | "D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpj1vyu8hf"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Esp-idf\\Espressif\\python_env\\idf5.4_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\ADMIN\\AppData\\Local\\Temp\\tmpj1vyu8hf': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40380838: esp_restart_noos at D:/Esp-idf/Espressif/frameworks/esp-idf-v5.4/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0m
